CFLAGS := gcc -std=gnu11 -Wall -Wextra

null: null.c
	$(CFLAGS) null.c -o null
ex4: ex4.c
	$(CFLAGS) ex4.c -o ex4
ex5: ex5.c
	$(CFLAGS) ex5.c -o ex5
ex6: ex6.c
	$(CFLAGS) ex6.c -o ex6
ex7: ex7.c
	$(CFLAGS) ex7.c -o ex7
ex8: ex8.c
	$(CFLAGS) ex8.c -o ex8
clean:
	rm null ex4 ex5 ex6
