(define (pascal row col)
    (if (on-edge? row col)
      1
      (+ (pascal (- row 1) (- col 1))
         (pascal (- row 1) col))))

(define (on-edge? row col)
  (or (= col 1)
      (= row col)))

(display (pascal 1 1)) (newline)
(display (pascal 2 1)) (newline)
(display (pascal 2 2)) (newline)
(display (pascal 3 1)) (newline)
(display (pascal 3 2)) (newline)
(display (pascal 3 3)) (newline)
(display (pascal 4 1)) (newline)
(display (pascal 4 2)) (newline)
(display (pascal 4 3)) (newline)
(display (pascal 4 4)) (newline)
(display (pascal 5 1)) (newline)
(display (pascal 5 2)) (newline)
(display (pascal 5 3)) (newline)
(display (pascal 5 4)) (newline)
(display (pascal 5 5)) (newline)

