CFLAGS := gcc -std=gnu11 -Wall -Wextra

ex1: ex1.c
	$(CFLAGS) ex1.c -o ex1
	./ex1
ex2: ex2.c
	$(CFLAGS) ex2.c -o ex2
	./ex2
ex3: ex3.c
	$(CFLAGS) ex3.c -o ex3
	./ex3
ex4: ex4.c
	$(CFLAGS) ex4.c -o ex4
	./ex4
ex5: ex5.c
	$(CFLAGS) ex5.c -o ex5
	./ex5
ex6: ex6.c
	$(CFLAGS) ex6.c -o ex6
	./ex6
ex7: ex7.c
	$(CFLAGS) ex7.c -o ex7
	./ex7
ex8: ex8.c
	$(CFLAGS) ex8.c -o ex8
	./ex8
clean:
	rm ex1 ex2 ex3 ex4 ex5 ex6 ex7 ex8
