CFLAGS := gcc -std=gnu11 -Wall -Wextra

3-2: 3-2.c
	$(CFLAGS) 3-2.c -o 3-2

3-20: 3-20.c
	$(CFLAGS) 3-20.c -o 3-20

3-23: 3-23.c
	$(CFLAGS) 3-23.c -o 3-23

clean:
	rm -f ./*.o ./*.h.gch *.out
	rm -f ./3-2 ./3-20 ./3-23
