; The delay needed for the output is: n * ((2 * or-delay) + (2 * and-delay))
(define (ripple-carry-adder a b c-in s c-out)
  (define (rca a b s c)
    (if (null? (cdr a))
      (full-adder (car a) (car b) c-in (car s) c)
      (let ((w (make-wire)))
        (full-adder (car a) (car b) w (car s) c)
        (rca (cdr a) (cdr b) (cdr s) w))))
  (rca (reverse a) (reverse b) (reverse s) c-out))
