(define (make-account balance password)
  (let ((incorrect-count 0))
    (define (withdraw amount)
      (if (>= balance amount)
        (begin
          (set! balance (- balance amount))
          balance)
        "Insufficient Funds"))
    (define (deposit amount)
      (set! balance (+ balance amount))
      balance)
    (define (incorrect-password x)
      (if (>= incorrect-count 7)
        (call-the-cops)
        (begin
          (set! incorrect-count (+ incorrect-count 1))
          "Incorrect Password")))
    (define (call-the-cops)
      "Calling the cops")
    (define (dispatch p m)
      (if (eq? p password)
        (begin
          (set! incorrect-count 0)
          (cond ((eq? m 'withdraw) withdraw)
                ((eq? m 'deposit deposit))
                (else
                (error "Unknown request -- MAKE-ACCOUNT" m))))
        incorrect-password))
    dispatch))

(define acc (make-account 100 'secret-password))

(display ((acc 'secret-password 'withdraw) 50)) (newline)
(display ((acc 'secret 'withdraw) 50)) (newline)
(display ((acc 'secret 'withdraw) 50)) (newline)
(display ((acc 'secret 'withdraw) 50)) (newline)
(display ((acc 'secret 'withdraw) 50)) (newline)
(display ((acc 'secret 'withdraw) 50)) (newline)
(display ((acc 'secret 'withdraw) 50)) (newline)
(display ((acc 'secret 'withdraw) 50)) (newline)
(display ((acc 'secret 'withdraw) 50)) (newline)
